export interface AppVideoItem {
  id: string;
  title: string;
  author: string;
  authorAvatar?: string;
  channelId?: string;
  thumbnail: string;
  duration?: string;
  durationSeconds?: number;
  published?: string;
  viewCount?: string;
}

export interface PaginatedVideosResult {
  videos: AppVideoItem[];
  continuationToken?: string;
}

export interface StreamFormatOption {
  qualityLabel: string;
  url: string;
  hasVideo?: boolean;
  hasAudio?: boolean;
  mimeType?: string;
  bitrate?: number;
}

export interface AudioTrackOption {
  id: string;
  label: string;
  language?: string;
  url: string;
  isDefault?: boolean;
  mimeType?: string;
  bitrate?: number;
}

export interface CaptionTrackOption {
  id: string;
  languageCode: string;
  label: string;
  baseUrl: string;
  isAutoGenerated?: boolean;
}

export interface PlayableStreamResult {
  videoId: string;
  title: string;
  author: string;
  authorAvatar?: string;
  channelId?: string;
  description: string;
  durationSeconds: number;
  thumbnailUrl: string;
  streamUrl: string;
  audioStreamUrl?: string;
  audioTracks?: AudioTrackOption[];
  activeAudioTrackId?: string;
  downloadUrl?: string;
  captionTracks?: CaptionTrackOption[];
  dashManifestUri?: string;
  contentType?: 'auto' | 'progressive' | 'dash' | 'hls';
  availableQualities?: StreamFormatOption[];
  qualityLabel?: string;
  views?: string;
  published?: string;
  rawVideoFormats?: any[];
  rawAudioFormats?: any[];
  clientUserAgent?: string;
}

export interface ChannelPlaylistItem {
  id: string;
  title: string;
  videoCount?: string;
  thumbnail?: string;
}

export interface ChannelDetails {
  id: string;
  title: string;
  avatar?: string;
  banner?: string;
  subscriberCount?: string;
  videosCount?: string;
  description?: string;
  videos: AppVideoItem[];
  playlists: ChannelPlaylistItem[];
  continuationToken?: string;
}

export interface VideoComment {
  id: string;
  author: string;
  authorAvatar?: string;
  text: string;
  published?: string;
  likeCount?: string;
}
